// import { solution as solutionDay1 } from './day1/solution';
// import { solution as solutionDay2 } from './day2/solution';
// import { solution as solutionDay3 } from './day3/solution';
// import { solution as solutionDay4 } from './day4/solution';
// import { solution as solutionDay5 } from './day5/solution';
// import { solution as solutionDay6 } from './day6/solution';
// import { solution as solutionDay7 } from './day7/solution';
// import { solution as solutionDay8 } from './day8/solution';
// import { solution as solutionDay9 } from './day9/solution';
// import { solution as solutionDay10 } from './day10/solution';
// import { solution as solutionDay11 } from './day11/solution';
// import { solution as solutionDay12 } from './day12/solution';
// import { solution as solutionDay13 } from './day13/solution';
// import { solution as solutionDay14 } from './day14/solution';
import { solution as solutionDay15 } from './day15/solution';

// solutionDay1();
// solutionDay2();
// solutionDay3();
// solutionDay4();
// solutionDay5();
// solutionDay6();
// solutionDay7();
// solutionDay8();
// solutionDay9();
// solutionDay10();
// solutionDay11();
// solutionDay12();
// solutionDay13();
// solutionDay14();
solutionDay15();